### ISSUE TITLE
in video 07-nav, the nav bar doesn't show up the first time it's supposed to.

### ISSUE THREAD

**Issue by ghost** [jacekschae/learn-re-frame-course-files#8] opened 2020-05-11 08:49 UTC
I'm talking about timestamp 6:38.

I even swapped out with the correct code in the repo and it still doesn't work. There are no errors either in the console or on the screen or in the build. 

This is my core.cljs
```
(ns app.core
  (:require [reagent.core :as r]
            [re-frame.core :as rf]
            [app.db]
            [app.nav.views.nav :refer [nav]]
            [app.theme :refer [cheffy-theme]]
            ["@smooth-ui/core-sc" :refer [Normalize ThemeProvider Button]]))

(defn app
  []
  [:<>
   [:> Normalize]
   [:> ThemeProvider {:theme cheffy-theme}
    [nav]]])

(defn ^:dev/after-load start
  []
  (rf/dispatch-sync [:initialize-db])
  (r/render [app]
    (.getElementById js/document "app")))

(defn ^:export init
  []
  (start))
```

**Comment by jacekschae** [comment] 2020-05-11 09:03
Hi there,

Thanks for the issue. 

I think the problem is in `app.nav.views.nav`

```clojure
(ns app.nav.views.nav
  (:require [app.nav.views.authenticated :refer [authenticated]]))

(defn nav
  []
  (let [user true]
    (if user
      [authenticated] ; <-- make sure this is authenticated and not a string
      "public")))
```

**Comment by tiotolstoy** [comment] 2020-05-13 03:04
That worked, thank you so much!

I took the `cheffy` folder out of the repo and now I cannot build the app by running `yarn dev`. I thought cheffy was independent from the top level repo. This is my error:

```
[:app] Build failure:
Multiple files failed to compile.
aborted par-compile, [:shadow.build.classpath/resource "app/nav/views/nav.cljs"] still waiting for #{app.nav.views.authenticated}
{:aborted [:shadow.build.classpath/resource "app/nav/views/nav.cljs"], :pending #{app.nav.views.authenticated}}
ExceptionInfo: aborted par-compile, [:shadow.build.classpath/resource "app/nav/views/nav.cljs"] still waiting for #{app.nav.views.authenticated}
        shadow.build.compiler/par-compile-one (compiler.clj:995)
        shadow.build.compiler/par-compile-one (compiler.clj:960)
        shadow.build.compiler/par-compile-cljs-sources/fn--12142/iter--12164--12168/fn--12169/fn--12170/fn--12171 (compiler.clj:1078)
        clojure.core/apply (core.clj:665)
        clojure.core/with-bindings* (core.clj:1973)
```

**Comment by jacekschae** [comment] 2020-07-05 09:08
@tiotolstoy could we close this one?

**Comment by jacekschae** [comment] 2021-11-13 01:48
Stale

**Closed by jacekschae** 2021-11-13 01:48 UTC
